### ISSUE TITLE
Request: null-safety

### ISSUE THREAD

**Issue by giorgiofran** [denixport/dart-uuid#1]
Request: are you planning to release a null-safety version?

Thanks in advance

**Comment by denixport** [comment]
Definitely on the list, need to check with current NNBD status.

**Comment by viliusvig** [comment]
Any update on this? There's a [null-safety pull-request](https://github.com/denixport/dart-uuid/pull/2/commits/53544c65cde2c86ed8284f9a64308e65ff8f1364)

Would be great to have the support for flutter 2.0

**Comment by denixport** [comment]
Null-safe 2.0 update is released, please watch out for some API changes
